name: digilock_app 
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.5

  # Firebase dependencies
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  url_launcher: ^6.1.10

  webview_flutter: ^4.0.7
  video_player: ^2.6.1

  # File picker for uploads
  file_picker: ^10.1.2

  # Replaced EPUB viewer with the new 'epub' package
  flutter_pdfview: ^1.0.0
  http: ^1.3.0
  path_provider: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo_outlined.png

flutter_native_splash:
  color: "#0C1C30"
  image: assets/logo_outlined.png
  android: true
  ios: true
