// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3aY09aZHBRCga2TmvvstiyznHs_CDa5k',
    appId: '1:89502148227:web:181c7f399dbb94082b9db6',
    messagingSenderId: '89502148227',
    projectId: 'digilock-17538',
    authDomain: 'digilock-17538.firebaseapp.com',
    storageBucket: 'digilock-17538.firebasestorage.app',
    measurementId: 'G-KKZNLE0VFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHe5RVvin6FA9xX6w7oubL1a5HF1fKGQU',
    appId: '1:89502148227:android:40eead59f7a18bc62b9db6',
    messagingSenderId: '89502148227',
    projectId: 'digilock-17538',
    storageBucket: 'digilock-17538.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhOmHp-JIvxVjytNBBujr4DVIYvrLYs0U',
    appId: '1:89502148227:ios:fcae2585c645fe8b2b9db6',
    messagingSenderId: '89502148227',
    projectId: 'digilock-17538',
    storageBucket: 'digilock-17538.firebasestorage.app',
    iosBundleId: 'com.example.digilockApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhOmHp-JIvxVjytNBBujr4DVIYvrLYs0U',
    appId: '1:89502148227:ios:fcae2585c645fe8b2b9db6',
    messagingSenderId: '89502148227',
    projectId: 'digilock-17538',
    storageBucket: 'digilock-17538.firebasestorage.app',
    iosBundleId: 'com.example.digilockApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3aY09aZHBRCga2TmvvstiyznHs_CDa5k',
    appId: '1:89502148227:web:c6a53a3349ea85d62b9db6',
    messagingSenderId: '89502148227',
    projectId: 'digilock-17538',
    authDomain: 'digilock-17538.firebaseapp.com',
    storageBucket: 'digilock-17538.firebasestorage.app',
    measurementId: 'G-16Y9QWKYF6',
  );
}
